### PR TITLE
added public instance

### PR DESCRIPTION
**Pull request by igosad**

### CODE REVIEW

**Comment by Hunam6** [comment]
image

**Comment by igosad** [comment]
> image

The URL was `https://www.whoogle.tech/` and not `https://whoogle.tech/`.
 I changed then subdomain so it can be more clear .

**Review by benbusby — APPROVED** [review]
Looks good, thanks!

I'm planning on expanding the public instances list into a table with more information in the near future. Just to confirm, it looks like this instance is hosted in the US?

**Comment by igosad** [comment]
>this instance is hosted in the US?
Yes it is hosted on Google cloud servers + Cloudflare, and it will change IPs every 24 hours.

**Pull request merged**
