### PR TITLE
Add autofocus to input field

### PR DESCRIPTION
**Pull request by Kombustor**
Supported in all major browsers, allows the user to immediately start typing after loading the page.

### CODE REVIEW

**Comment by benbusby** [comment]
Just the one small comment. Let me know your thoughts and I'll merge accordingly.

**Comment by Kombustor** [comment]
This seems to be a firefox bug. I currently don't have it installed, but [it should be supported](https://caniuse.com/#feat=autofocus).

We could focus the element by using JS (``document.getElementById('search-bar').focus()` on page load), but this is certainly not the best solution. And it didn't work for me in Chrome using the console.

**Comment by Kombustor** [comment]
Does it work for you in firefox like this? @benbusby

**Comment by benbusby** [comment]
Hmmm no, the updated autofocus field didn't fix it. I'll still merge this in since it seems to be working everywhere else, but I'll make a separate issue for looking into it further on Firefox. 

Thanks for contributing!

**Pull request merged**
