### PR TITLE
Project refactor (#85) -> master

### PR DESCRIPTION
**Pull request by benbusby**
* Major refactor of requests and session management

- Switches from pycurl to requests library
  - Allows for less janky decoding, especially with non-latin character
  sets
- Adds session level management of user configs
  - Allows for each session to set its own config (people are probably
  going to complain about this, though not sure if it'll be the same
  number of people who are upset that their friends/family have to share
  their config)
- Updates key gen/regen to more aggressively swap out keys after each
request

* Added ability to save/load configs by name

- New PUT method for config allows changing config with specified name
- New methods in js controller to handle loading/saving of configs

* Result formatting and removal of unused elements

- Fixed question section formatting from results page (added appropriate
padding and made questions styled as italic)
- Removed user agent display from main config settings

* Minor change to button label

* Fixed issue with "de-pickling" of flask session

Having a gitignore-everything ("*") file within a flask session folder seems to cause a
weird bug where the state of the app becomes unusable from continuously
trying to prune files listed in the gitignore (and it can't prune '*').

* Switched to pickling saved configs

* Updated ad/sponsored content filter and conf naming

Configs are now named with a .conf extension to allow for easier manual
cleanup/modification of named config files

Sponsored content now removed by basic string matching of span content

* Version bump to 0.2.0

* Fixed request.send return style

### CODE REVIEW

**Comment by FoxxMD** [comment]
I'm on `beta` tag on dockerhub. Only config didn't work but that was to be expected. New config save/loading works well! And all the other fancy new features (autocomplete, spelling correct) are awesome! Great work!

Only issue I've seen so far is that every request to whoogle without using a named config produces a new session file. Like, every single one (autocomplete, page browsing, etc.) This is just a few minutes browsing around -- my folder is already up to 30kb of files.
image

**Comment by FoxxMD** [comment]
Images also aren't loading and cause the page to hang for a bit (eventually recovers). Maybe related to this trace:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 104, in _verify_signature
h.verify(data[-32:])
File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
ctx.verify(signature)
File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/src/app/app/routes.py", line 32, in decorated
return f(*args, **kwargs)
File "/usr/src/app/app/routes.py", line 200, in element
src_url = cipher_suite.decrypt(request.args.get('url').encode()).decode()
File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 75, in decrypt
return self._decrypt_data(data, timestamp, ttl)
File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
self._verify_signature(data)
File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 106, in _verify_signature
raise InvalidToken
cryptography.fernet.InvalidToken
ERROR:app:Exception on /element [GET]
```

**Comment by benbusby** [comment]
@FoxxMD thanks a million for testing this out already! 

Regarding the session files being generated for every request, I've actually encountered this before and it seemed to be related to my browser blocking cookies for my instance of whoogle-search (and so a new "session" was created on every api call). And since the element and text keys are tied to user sessions now, that would explain why some images aren't decrypting properly and you're seeing the encrypted search string when navigating between tabs. Any chance this might be the case with your setup?

I should probably revisit the logic behind all of this and ensure it works similarly for any browsers that don't allow setting cookies for the instance (or otherwise just aren't passing the session value between api calls properly).

**Comment by FoxxMD** [comment]
Yep you nailed it. One of my extensions (Privacy Bader, ublock origin) was not letting the cookie be set but they also weren't showing anything being blocked.

**Comment by benbusby** [comment]
Hmmm, that's interesting. I have both extensions active and haven't experienced cookies for Whoogle being blocked yet. Either way I plan to look into this quite a bit more before merging though.

**Comment by FoxxMD** [comment]
If it helps at all I'm using this from my own domain (subdomain.mydomain.com) rather than accessing through IP

**Comment by benbusby** [comment]
@FoxxMD I couldn't accurately track down a specific reason for why occasionally browsers might reject cookies from whoogle, but I updated this anyways to include fallback support for browsers that aren't allowing cookies to be set for one reason or another. Now anyone who uses whoogle but isn't able to (or doesn't want to) allow cookies for the site will trigger the "legacy" version of the app, which just uses the old method of using a static config file and a one-time generated key set. Hopefully this mitigates the issue you were seeing originally. I'll include a short write-up about these changes in the release documentation once I merge.

**Pull request merged**
