### PR TITLE
add basic keyboard support

### PR DESCRIPTION
**Pull request by tborychowski**
This adds basic keyboard support on the search results page:
- `ArrowUp` or `k` - focus previous result
- `ArrowDown` or `j` - focus next result
- `/` focus search box

Because this just focuses links in the search result items hitting `Enter` (or ctrl/cmd + Enter) when an item is focused - will open the search result (because the link is already focused and this is browser's default behaviour).

### CODE REVIEW

**Comment by benbusby** [comment]
Thanks for implementing this, I'm definitely a fan. 

One issue though -- the `j` and `k` navigation is still active when the search input is focused, so typing either letter triggers the navigation action rather than modifying the query with the new letter. Once that's been fixed I think this should be good to go.

**Comment by tborychowski** [comment]
Ha! Sorry about that! :-)
That's the one-man testing 😛
Will fix later today.

**Comment by tborychowski** [comment]
@benbusby should be good now. Thanks!

**Review by benbusby — APPROVED** [review]
Awesome, thanks! Looks great.

**Pull request merged**
