### PR TITLE
දෝෂ කිහිපයක් නිවරදි කිරීම

### PR DESCRIPTION
**Pull request by sayuri-gi**
@benbusby you need to add full sentence to 38 line as **search with farside** or **search with %name%** etc because we need to write it as **farside සමඟ සෙවුම කරගෙන යන්න.** let me know once that fixed before merge this PR https://github.com/benbusby/whoogle-search/blob/362b6a75c85f73c447ff4b801cdbb15d26b2ec3a/app/static/settings/translations.json#L38

### CODE REVIEW

**Comment by nakoo** [comment]
You should change the title to English. Otherwise, no one knows what is supposed to do.
I believe this is the translation error?

**Comment by sayuri-gi** [comment]
@nakoo i didn't get what you mean, can you clarify?

**Comment by Albonycal** [comment]
I think that means 
`Fix some bugs`

**Comment by benbusby** [comment]
@sayuri-gi I pushed changes to your branch to include the "Farside" service name in the translation string. Let me know if that looks good to you and I'll merge.

**Comment by sayuri-gi** [comment]
It's correct now

**Review by benbusby — APPROVED** [review]

**Pull request merged**
